import { GradientBackgroundCon } from "@/components/quoteGenerator/quoteGeneratorElement";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>quote generator</title>
        <meta name="description" content="project to generate quotes" />
        <meta name="viewport" content="Generated by create next app" />
      </Head>
      <GradientBackgroundCon></GradientBackgroundCon>
    </>
  );
}
